// Generated by CoffeeScript 2.5.1
(function() {
  var browser, closePage, gotoPage, localServer, makeServer, page, puppeteer, sleep, waitForRendered, ws;

  localServer = require('local-web-server');

  puppeteer = require('puppeteer');

  global.navigator = {
    userAgent: 'summat'
  };

  browser = null;

  page = null;

  ws = null;

  makeServer = function(path) {
    return ws = localServer.create({
      port: 23232,
      directory: path,
      spa: 'index.html'
    });
  };

  gotoPage = async function(path, puppeteerOptions) {
    browser = (await puppeteer.launch(puppeteerOptions));
    page = (await browser.newPage());
    return (await page.goto('http://localhost:23232/' + (path || '')));
  };

  closePage = async function() {
    await browser.close();
    return ws.server.close();
  };

  waitForRendered = async function() {
    return (await page.evaluate(function() {
      return new Promise(function(resolve) {
        window.app.$once('rendered', function() {
          return resolve();
        });
        return window.app.render();
      });
    }));
  };

  sleep = function(time) {
    return new Promise(function(resolve) {
      return setTimeout(resolve, time);
    });
  };

  exports.ymaCoreTest = {
    "Should autofocus first input": async function(test) {
      makeServer('test/autofocus');
      await gotoPage('');
      await waitForRendered();
      test.ok((await page.evaluate(function() {
        return document.querySelectorAll('input')[0] === document.activeElement;
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelectorAll('input')[1] !== document.activeElement;
      })));
      await closePage();
      return test.done();
    },
    "Should display home scene": async function(test) {
      var str;
      makeServer('test/router-basic');
      await gotoPage('');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return document.querySelector('app').innerText;
      }));
      test.equals(str, 'home');
      await closePage();
      return test.done();
    },
    "Should display about scene": async function(test) {
      var str;
      makeServer('test/router-basic');
      await gotoPage('about');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return document.querySelector('app').innerText;
      }));
      test.equals(str, 'about');
      await closePage();
      return test.done();
    },
    "Should display users scene": async function(test) {
      var str;
      makeServer('test/router-basic');
      await gotoPage('users');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return document.querySelector('app').innerText;
      }));
      test.equals(str, 'users');
      await closePage();
      return test.done();
    },
    "Should display router component": async function(test) {
      var str;
      makeServer('test/router-components');
      await gotoPage('');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return document.querySelector('router').innerText;
      }));
      test.equals(str, 'home');
      await closePage();
      return test.done();
    },
    "Should display router about component": async function(test) {
      var str;
      makeServer('test/router-components');
      await gotoPage('about');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return document.querySelector('router').innerText;
      }));
      test.equals(str, 'about');
      await closePage();
      return test.done();
    },
    "Should display home scene (update)": async function(test) {
      var str;
      makeServer('test/router-update');
      await gotoPage('');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return document.querySelector('router').innerText;
      }));
      test.equals(str, 'home');
      await closePage();
      return test.done();
    },
    "Should display about scene (update)": async function(test) {
      var str;
      makeServer('test/router-update');
      await gotoPage('');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            return resolve(document.querySelector('router').innerText);
          });
          return document.querySelector('#goAbout').click();
        });
      }));
      test.equals(str, 'about');
      await closePage();
      return test.done();
    },
    "Should display about scene then go home (update)": async function(test) {
      var str;
      makeServer('test/router-update');
      await gotoPage('');
      await waitForRendered();
      str = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            window.app.$once('updated', function() {
              return resolve(document.querySelector('router').innerText);
            });
            return document.querySelector('#goHome').click();
          });
          return document.querySelector('#goAbout').click();
        });
      }));
      test.equals(str, 'home');
      await closePage();
      return test.done();
    },
    "Should press a button and update scope variable": async function(test) {
      var val;
      makeServer('test/press-basic');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            return resolve(document.querySelector('h1').innerHTML);
          });
          return document.querySelector('a').click();
        });
      }));
      test.equals(val, 'boom');
      await closePage();
      return test.done();
    },
    "Should do a basic repeater test": async function(test) {
      var val;
      makeServer('test/repeater-basic');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return document.querySelector('app').innerHTML;
      }));
      test.equals(val, '<h1>0 BARRY</h1><h1>1 BUDDY</h1><h1>2 MAGGIE</h1><h1>3 TEDDY</h1>');
      await closePage();
      return test.done();
    },
    "Should do a large repeater test": async function(test) {
      var val;
      makeServer('test/repeater-large');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return document.querySelectorAll('h1').length;
      }));
      test.equals(val, 10000);
      await closePage();
      return test.done();
    },
    "Should test repeater updating": async function(test) {
      var val;
      makeServer('test/repeater-update');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return document.querySelectorAll('h2').length;
      }));
      test.equals(val, 6);
      await closePage();
      return test.done();
    },
    "Should test repeater updating - add one": async function(test) {
      var val;
      makeServer('test/repeater-update');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            return resolve(document.querySelectorAll('h2').length);
          });
          return document.getElementById('more').click();
        });
      }));
      test.equals(val, 7);
      await closePage();
      return test.done();
    },
    "Should test repeater updating - minus one": async function(test) {
      var val;
      makeServer('test/repeater-update');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            return resolve(document.querySelectorAll('h2').length);
          });
          return document.getElementById('less').click();
        });
      }));
      test.equals(val, 5);
      await closePage();
      return test.done();
    },
    "Should test component repeater updating": async function(test) {
      var val;
      makeServer('test/repeater-update-component');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return document.querySelectorAll('h2').length;
      }));
      test.equals(val, 6);
      await closePage();
      return test.done();
    },
    "Should test component repeater updating - add one": async function(test) {
      var val;
      makeServer('test/repeater-update-component');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            return resolve(document.querySelectorAll('h2').length);
          });
          return document.getElementById('more').click();
        });
      }));
      test.equals(val, 7);
      await closePage();
      return test.done();
    },
    "Should test component repeater updating - minus one": async function(test) {
      var val;
      makeServer('test/repeater-update-component');
      await gotoPage('');
      await waitForRendered();
      val = (await page.evaluate(function() {
        return new Promise(function(resolve) {
          window.app.$once('updated', function() {
            return resolve(document.querySelectorAll('h2').length);
          });
          return document.getElementById('less').click();
        });
      }));
      test.equals(val, 5);
      await closePage();
      return test.done();
    }
  };

}).call(this);
