// Generated by CoffeeScript 2.5.1
(function() {
  var browser, closePage, gotoPage, localServer, makeServer, page, puppeteer, waitForRendered, ws;

  localServer = require('local-web-server');

  puppeteer = require('puppeteer');

  global.navigator = {
    userAgent: 'summat'
  };

  browser = null;

  page = null;

  ws = null;

  makeServer = function(path) {
    return ws = localServer.create({
      port: 23232,
      directory: path,
      spa: 'index.html'
    });
  };

  gotoPage = async function(path) {
    browser = (await puppeteer.launch());
    page = (await browser.newPage());
    return (await page.goto('http://localhost:23232/' + (path || '')));
  };

  closePage = async function() {
    await browser.close();
    return ws.server.close();
  };

  waitForRendered = async function() {
    return (await page.evaluate(function() {
      return new Promise(function(resolve) {
        window.app.$on('rendered', function() {
          return resolve();
        });
        return window.app.render();
      });
    }));
  };

  exports.ymaCoreTest = {
    "Should autofocus first input": async function(test) {
      makeServer('test/autofocus');
      await gotoPage('');
      await waitForRendered();
      test.ok((await page.evaluate(function() {
        return document.querySelectorAll('input')[0] === document.activeElement;
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelectorAll('input')[1] !== document.activeElement;
      })));
      await closePage();
      return test.done();
    },
    "Should display home scene": async function(test) {
      makeServer('test/router-basic');
      await gotoPage('');
      await waitForRendered();
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="home"].yma-router-active');
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="about"].yma-router-parked');
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="users"].yma-router-parked');
      })));
      await closePage();
      return test.done();
    },
    "Should display about scene": async function(test) {
      makeServer('test/router-basic');
      await gotoPage('about');
      await waitForRendered();
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="about"].yma-router-active');
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="home"].yma-router-parked');
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="users"].yma-router-parked');
      })));
      await closePage();
      return test.done();
    },
    "Should display users scene": async function(test) {
      makeServer('test/router-basic');
      await gotoPage('users');
      await waitForRendered();
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="users"].yma-router-active');
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="home"].yma-router-parked');
      })));
      test.ok((await page.evaluate(function() {
        return document.querySelector('scene[name="about"].yma-router-parked');
      })));
      await closePage();
      return test.done();
    }
  };

}).call(this);
