// Generated by CoffeeScript 2.5.1
(function() {
  var Yma;

  Yma = require('yma');

  window.app = Yma('myApp').component(require('../../../dist/index')).component('app', function(app) {
    return {
      controller: function(scope) {
        scope.noThings = 6;
        return scope.date = new Date();
      }
    };
  });

}).call(this);
