// Generated by CoffeeScript 2.5.1
(function() {
  var Yma;

  Yma = require('yma');

  window.app = Yma('myApp').component(require('../../../dist/index')).component('app', function(app) {
    return {
      controller: function(scope) {
        return scope.testVar = 'bazaza';
      }
    };
  });

}).call(this);
