// Generated by CoffeeScript 2.5.1
(function() {
  var Yma;

  Yma = require('yma');

  window.app = Yma('myApp').component(require('../../../dist/index')).component('about', function(app) {
    return {
      controller: function(scope) {}
    };
  });

}).call(this);
