// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = function(app) {
    return {
      template: '<header><menu></menu></header><router><div class="home" scene="home" component="home" route="/" default="default"><h1>home</h1></div><div class="about" scene="about" component="about" route="/about"><h1>about</h1></div></router><footer></footer>'
    };
  };

}).call(this);
