// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = function(app) {
    return {
      template: '<header><menu></menu></header><router><scene name="home" component="home" route="/" default="default"><h1>home</h1></scene><scene name="about" component="about" route="/about"><h1>about</h1></scene></router><footer></footer>'
    };
  };

}).call(this);
