// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = function(app) {
    return {
      template: '<h1>meeenz</h1><a go="/">home</a><a go="/about">about</a>'
    };
  };

}).call(this);
